apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-docker-client
spec:
  containers:
    - name: jenkins-docker-client
      image: trion/jenkins-docker-client
      command:
        - cat
      tty: true
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"