apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-agent
spec:
  containers:
    - name: jenkins-agent
      # image: trion/jenkins-docker-client
      image: reg.pointit.co.th/jenkins-agent:2.0.0
      command:
        - cat
      tty: true
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"
      volumeMounts:
        # directory location on Docker
      - mountPath: /var/run/docker.sock
        name: docker
  volumes:
  - name: docker
    hostPath:
      # directory location on host
      path: /var/run/docker.sock