apiVersion: v1
kind: Pod
metadata:
  labels:
    app: xyz
spec:
  containers:
    - name: alpine
      image: alpine
      command:
        - cat
      tty: true
      resources:
        limits:
          memory: 512Mi
          cpu: "0.5"
        requests:
          memory: 256Mi
          cpu: "0.2"