apiVersion: v1
kind: Service
metadata:
  name: eks
spec:
  type: LoadBalancer
  selector:
    app: eks
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks
  labels:
    app: eks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks
  template:
    metadata:
      labels:
        app: eks
    spec:
      containers:
      - name: nginx
        image: 378537635200.dkr.ecr.ap-southeast-1.amazonaws.com/eks
        ports:
        - containerPort: 80