apiVersion: v1
kind: Pod
metadata:
  labels:
    app: python
spec:
  containers:
    - name: python
      image: trion/jenkins-docker-client
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"