apiVersion: v1
kind: Service
metadata:
  name: FrontEnd
spec:
  type: LoadBalancer
  selector:
    app: nuxtjs
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntadmin
  namespace: ntadmin
  labels:
    app: nuxtjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nuxtjs
  template:
    metadata:
      labels:
        app: nuxtjs
    spec:
      containers:
      - name: ntadmin
        image: reg.pointit.co.th/ntadmin:1.0.1
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 512Mi
            cpu: "0.5"
          requests:
            memory: 256Mi
            cpu: "0.2"