apiVersion: v1
kind: Service
metadata:
  name: FrontEnd
spec:
  type: LoadBalancer
  selector:
    app: nuxtjs
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservice
  labels:
    app: nuxtjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nuxtjs
  template:
    metadata:
      labels:
        app: nuxtjs
    spec:
      containers:
      - name: nginx
        image: 378537635200.dkr.ecr.ap-southeast-1.amazonaws.com/eck
        ports:
        - containerPort: 80