kind: Deployment
metadata:
  name: jenkins-agent
  labels:
    app.kubernetes.io/name: jenkins-agent
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: jenkins-agent
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jenkins-agent
    spec:
      containers:
      - image: reg.pointit.co.th/ntmobile:1.0.0
        name: jenkins-agent
        ports:
        - containerPort: 1880
          name: http
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-agent-svc
spec:
#  externalTrafficPolicy: Local #Use For NodePort or LoadBalancer mode
  ports:
  - name: http
    port: 1880
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: jenkins-agent
  sessionAffinity: None
  type: LoadBalancer