apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kube
spec:
  containers:
    - name: kube
      image: jenkins/inbound-agent:4.11.2-4
      command:
        - sleep
      tty: true
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"