apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapps
  labels:
    app: webapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapps
  template:
    metadata:
      labels:
        app: webapps
    spec:
      containers:
      - name: webapps
        image: 378537635200.dkr.ecr.ap-southeast-1.amazonaws.com/eks:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: webapps-svc
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: webapps
  sessionAffinity: None
  type: LoadBalancer